parameters:
- name: verifyOnly
  type: boolean
  default: false

stages:
- stage: SynchronizeSecrets
  displayName: Synchronize Secrets
  dependsOn: []
  jobs:
  - job: Synchronize
    displayName: Synchronize Secrets
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2022

    variables:
    - ${{ if parameters.verifyOnly }}:
      - name: secretManagerArgs
        value: --verify-only
    - ${{ else }}:
      - name: secretManagerArgs
        value: ''

    steps:
    - powershell: |
        .\eng\common\build.ps1 -restore
        .\.dotnet\dotnet tool restore
      displayName: Install Secret Manager

    - task: AzureCLI@2
      displayName: Synchronize Secrets
      inputs:
        azureSubscription: DotNet Eng Services Secret Manager
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          Get-ChildItem .vault-config/*.yaml |% { .\.dotnet\dotnet secret-manager synchronize $(secretManagerArgs) $_ }