name: Copilot Setup Steps

# These steps will be executed before GitHub Copilot assists with code
# This helps ensure Copilot has access to properly restored dependencies

steps:
- name: Checkout repository
  uses: actions/checkout@v3
  with:
    fetch-depth: 0

- name: Setup .NET SDK
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: '8.0.x'
