name: Copilot Setup Steps

# These steps will be executed before GitHub Copilot assists with code
# This helps ensure Copilot has access to properly restored dependencies

steps:
- name: Checkout repository
  uses: actions/checkout@v3
  with:
    fetch-depth: 0

- name: Restore dependencies
  run: |
    ./eng/common/build.sh -restore
  shell: bash
