name: $(Date:yyy-MM-dd)$(Rev:.r)
appendCommitMessageToRunName: false

trigger: none

schedules:
- cron: 0 12 * * 1
  displayName: Weekly Monday build
  branches:
    include:
    - main
  always: true

stages:
  - stage: SynchronizeSecrets
    displayName: Synchronize Secrets
    jobs:
    - job: Synchronize
      displayName: Synchronize Secrets
      pool:
        name: NetCore1ESPool-Internal-NoMSI
        demands: ImageOverride -equals 1es-windows-2022
      steps:
      - powershell: |
          . .\eng\common\tools.ps1
          InitializeDotNetCli -install $true
          .\.dotnet\dotnet tool restore
        displayName: Install Secret Manager

      - task: AzureCLI@2
        displayName: Synchronize Secrets
        inputs:
          azureSubscription: DotNet Eng Services Secret Manager
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            Get-ChildItem .vault-config/*.yaml |% { .\.dotnet\dotnet secret-manager synchronize $_ }
