variables:
- name: _TeamName
  value: DotNetCore
- name: _PublishUsingPipelines
  value: true
- name: _DotNetArtifactsCategory
  value: .NETCore
- name: AzdoOrgUri
  value: https://dev.azure.com/dnceng
- name: AzdoProject
  value: internal
- name: resourceGroupName
  value: product-construction-service
- name: containerName
  value: product-construction-service.api

trigger:
  branches:
    exclude:
    - main
    - production

extends:
  template: azure-pipelines-shared.yml@self