name: $(Date:yyy-MM-dd)$(Rev:.r)
appendCommitMessageToRunName: false

trigger: none

schedules:
- cron: 0 6 * * 1
  displayName: Weekly Monday build
  branches:
    include:
    - main
  always: true

stages:
- template: /eng/templates/stages/secret-validation.yml
