trigger: none

schedules:
- cron: 0 12 * * 1
  displayName: Weekly Monday build
  branches:
    include:
    - main
  always: true

name: $(Date:yyyMMdd)$(Rev:rr)
resources:
  pipelines:
  - pipeline: arcadeServicesInternalCI
    source: arcade-services-internal-ci
    branch: main

stages:
  - stage: SynchronizeSecrets
    jobs:
    - job: Synchronize
      pool: 
        name: NetCore1ESPool-Internal-NoMSI
        demands: ImageOverride -equals 1es-windows-2019
      steps:
      - task: UseDotNet@2
        displayName: Install Correct .NET Version
        inputs:
          useGlobalJson: true

      - script: - script: dotnet tool restore
        displayName: Install DotNet Tools 

      - task: AzureCLI@2
        inputs:
          azureSubscription: DotNet Eng Services Secret Manager
          scriptType: ps
          scriptLocation: inlineScript
          inlineScript: |
            Get-ChildItem .vault-config/*.yaml |% { dotnet secret-manager synchronize $_ }
