version: '3.4'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: "azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log"
    hostname: azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001

  maestro.containerapp:
    image: ${DOCKER_REGISTRY-}maestrocontainerapp
    container_name: Maestro.ContainerApp
    build:
      context: .
      dockerfile: src/Maestro/Maestro.ContainerApp/Dockerfile
    depends_on:
      - azurite
    links:
      - azurite
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
