variables:
  # Cannot use key:value syntax in root defined variables
  - name: _TeamName
    value: DotNetCore
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: .NETCore
  # This can be overridden if we are using a locally built fork
  - group: Dotnet Grafana
  # Variables we want to be settable, so can't be defined here:
  # GrafanaBinPath: ""
  # TargetVmName: grafana
  # TargetResourceGroup: monitoring

stages:
- stage: deploy
  displayName: Deploy grafana server
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: false
      enablePublishBuildArtifacts: false
      enablePublishTestResults: false
      enablePublishBuildAssets: false
      enablePublishUsingPipelines: ${{ variables._PublishUsingPipelines }}
      enableTelemetry: false
      helixRepo: dotnet/arcade-services
      jobs:
      - job: Windows_NT
        timeoutInMinutes: 90
        pool:
          vmImage: windows-2019

        steps:
        - checkout: self
          clean: true

        - powershell: |
            if (-not (Test-Path env:GrafanaBinPath)) { Write-Host "Missing GrafanaBinPath, ensure required variables are defined"; exit 1}
            if (-not (Test-Path env:TargetVmName)) { Write-Host "Missing TargetVmName, ensure required variables are defined"; exit 1}
            if (-not (Test-Path env:TargetResourceGroup)) { Write-Host "Missing TargetResourceGroup, ensure required variables are defined"; exit 1}
            Write-Host "All required variables defined"
          displayName: Ensure variables defined

        - task: AzureFileCopy@3
          displayName: Copy grafana-init to VM
          inputs:
            sourcePath: $(Build.SourcesDirectory)\src\Monitoring\grafana-init
            azureSubscription: DncEng-VSTS
            storage: dotnetgrafana
            containerName: build-transfer
            blobPrefix: grafana-init-$(Build.BuildNumber)/
            destination: azureVMs
            resourceGroup: $(TargetResourceGroup)
            resourceFilteringMethod: machineNames
            machineNames: $(TargetVmName)
            vmsAdminUserName: grafana-admin
            vmsAdminPassword: $(grafana-admin-password)
            targetPath: /tmp/grafana-init/

        - task: AzureCLI@2
          displayName: Execute grafana-init/setup.sh on VM
          inputs:
            azureSubscription: DncEng-VSTS
            scriptType: batch
            scriptLocation: inlineScript
            inlineScript: >-
              az vm run-command invoke
              -g $(TargetResourceGroup)
              -n $(TargetVmName)
              --command-id RunShellScript
              --scripts "sudo bash /tmp/grafana-init/setup.sh $(GrafanaBinPath)"
