parameters:
  enableSourceLinkValidation: false
  enableSigningValidation: true
  enableSymbolValidation: false
  enableNugetValidation: true
  publishInstallersAndChecksums: false
  SDLValidationParameters:
    enable: false
    continueOnError: false
    params: ''
    artifactNames: ''
    downloadArtifacts: true

  # These parameters let the user customize the call to sdk-task.ps1 for publishing
  # symbols & general artifacts as well as for signing validation
  symbolPublishingAdditionalParameters: ''
  artifactsPublishingAdditionalParameters: ''
  signingValidationAdditionalParameters: ''
  useBuildManifest: false

  # Which stages should finish execution before post-build stages start
  validateDependsOn:
  - build
  publishDependsOn: 
  - Validate

  # Channel ID's instantiated in this file.
  # When adding a new channel implementation the call to `check-channel-consistency.ps1` 
  # needs to be updated with the new channel ID
  NetEngLatestChannelId: 2
  NetEngValidationChannelId: 9
  NetDev5ChannelId: 131
  GeneralTestingChannelId: 529
  NETCoreToolingDevChannelId: 548
  NETCoreToolingReleaseChannelId: 549
  NETInternalToolingChannelId: 551
  NETCoreExperimentalChannelId: 562
  NetEngServicesIntChannelId: 678
  NetEngServicesProdChannelId: 679
  Net5Preview3ChannelId: 739
  Net5Preview4ChannelId: 856
  Net5Preview5ChannelId: 857
  NetCoreSDK314xxChannelId: 921
  NetCoreSDK314xxInternalChannelId: 922
  
stages:
- stage: Validate
  dependsOn: ${{ parameters.validateDependsOn }}
  displayName: Validate
  variables:
    - template: common-variables.yml
  jobs:
  - template: setup-maestro-vars.yml

  - job:
    displayName: Post-build Checks
    dependsOn: setupMaestroVars
    variables:
      - name: TargetChannels
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.TargetChannels'] ]
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: PowerShell@2
        displayName: Maestro Channels Consistency
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/post-build/check-channel-consistency.ps1
          arguments: -PromoteToChannels "$(TargetChannels)"
            -AvailableChannelIds ${{parameters.NetEngLatestChannelId}},${{parameters.NetEngValidationChannelId}},${{parameters.NetDev5ChannelId}},${{parameters.GeneralTestingChannelId}},${{parameters.NETCoreToolingDevChannelId}},${{parameters.NETCoreToolingReleaseChannelId}},${{parameters.NETInternalToolingChannelId}},${{parameters.NETCoreExperimentalChannelId}},${{parameters.NetEngServicesIntChannelId}},${{parameters.NetEngServicesProdChannelId}},${{parameters.Net5Preview3ChannelId}},${{parameters.Net5Preview4ChannelId}},${{parameters.Net5Preview5ChannelId}},${{parameters.NetCoreSDK314xxChannelId}},${{parameters.NetCoreSDK314xxInternalChannelId}}

  - job:
    displayName: NuGet Validation
    dependsOn: setupMaestroVars
    condition: eq( ${{ parameters.enableNugetValidation }}, 'true')
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: AzDOProjectName
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
      - name: AzDOPipelineId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
      - name: AzDOBuildId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: specific
          buildVersionToDownload: specific
          project: $(AzDOProjectName)
          pipeline: $(AzDOPipelineId)
          buildId: $(AzDOBuildId)
          artifactName: PackageArtifacts

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/post-build/nuget-validation.ps1
          arguments: -PackagesPath $(Build.ArtifactStagingDirectory)/PackageArtifacts/ 
            -ToolDestinationPath $(Agent.BuildDirectory)/Extract/ 

  - job:
    displayName: Signing Validation
    dependsOn: setupMaestroVars
    condition: eq( ${{ parameters.enableSigningValidation }}, 'true')
    variables:
      - template: common-variables.yml
      - name: AzDOProjectName
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
      - name: AzDOPipelineId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
      - name: AzDOBuildId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
    pool:
      vmImage: 'windows-2019'
    steps:
      - ${{ if eq(parameters.useBuildManifest, true) }}:
        - task: DownloadBuildArtifacts@0
          displayName: Download build manifest
          inputs:
            buildType: specific
            buildVersionToDownload: specific
            project: $(AzDOProjectName)
            pipeline: $(AzDOPipelineId)
            buildId: $(AzDOBuildId)
            artifactName: BuildManifests
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: specific
          buildVersionToDownload: specific
          project: $(AzDOProjectName)
          pipeline: $(AzDOPipelineId)
          buildId: $(AzDOBuildId)
          artifactName: PackageArtifacts

      # This is necessary whenever we want to publish/restore to an AzDO private feed
      # Since sdk-task.ps1 tries to restore packages we need to do this authentication here
      # otherwise it'll complain about accessing a private feed.
      - task: NuGetAuthenticate@0
        displayName: 'Authenticate to AzDO Feeds'

      - task: PowerShell@2
        displayName: Enable cross-org publishing
        inputs:
          filePath: eng\common\enable-cross-org-publishing.ps1
          arguments: -token $(dn-bot-dnceng-artifact-feeds-rw)

      # Signing validation will optionally work with the buildmanifest file which is downloaded from
      # Azure DevOps above.
      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: eng\common\sdk-task.ps1
          arguments: -task SigningValidation -restore -msbuildEngine vs
            /p:PackageBasePath='$(Build.ArtifactStagingDirectory)/PackageArtifacts'
            /p:SignCheckExclusionsFile='$(Build.SourcesDirectory)/eng/SignCheckExclusionsFile.txt'
            ${{ parameters.signingValidationAdditionalParameters }}

      - template: ../steps/publish-logs.yml
        parameters:
          StageLabel: 'Validation'
          JobLabel: 'Signing'

  - job:
    displayName: SourceLink Validation
    dependsOn: setupMaestroVars
    condition: eq( ${{ parameters.enableSourceLinkValidation }}, 'true')
    variables:
      - template: common-variables.yml
      - name: AzDOProjectName
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
      - name: AzDOPipelineId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
      - name: AzDOBuildId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Blob Artifacts
        inputs:
          buildType: specific
          buildVersionToDownload: specific
          project: $(AzDOProjectName)
          pipeline: $(AzDOPipelineId)
          buildId: $(AzDOBuildId)
          artifactName: BlobArtifacts

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/post-build/sourcelink-validation.ps1
          arguments: -InputPath $(Build.ArtifactStagingDirectory)/BlobArtifacts/ 
            -ExtractPath $(Agent.BuildDirectory)/Extract/ 
            -GHRepoName $(Build.Repository.Name) 
            -GHCommit $(Build.SourceVersion)
            -SourcelinkCliVersion $(SourceLinkCLIVersion)
        continueOnError: true

  - template: /eng/common/templates/job/execute-sdl.yml
    parameters:
      enable: ${{ parameters.SDLValidationParameters.enable }}
      dependsOn: setupMaestroVars
      additionalParameters: ${{ parameters.SDLValidationParameters.params }}
      continueOnError: ${{ parameters.SDLValidationParameters.continueOnError }}
      artifactNames: ${{ parameters.SDLValidationParameters.artifactNames }}
      downloadArtifacts: ${{ parameters.SDLValidationParameters.downloadArtifacts }}

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net_Eng_Services_Int_Publish'
    channelName: '.NET Eng Services - Int'
    channelId: ${{ parameters.NetEngServicesIntChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net_Eng_Services_Prod_Publish'
    channelName: '.NET Eng Services - Prod'
    channelId: ${{ parameters.NetEngServicesProdChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    BARBuildId: ${{ parameters.BARBuildId }}
    PromoteToChannelIds: ${{ parameters.PromoteToChannelIds }}    
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'General_Testing_Publish'
    channelName: 'General Testing'
    akaMSChannelName: 'generaltesting'
    channelId: ${{ parameters.GeneralTestingChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing-symbols/nuget/v3/index.json'
