// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using Microsoft.AspNetCore.ApiPagination;
using Microsoft.AspNetCore.ApiVersioning;
using Microsoft.AspNetCore.ApiVersioning.Swashbuckle;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;
using Swashbuckle.AspNetCore.Swagger;

namespace Maestro.Web
{
    public partial class Startup
    {
        private void ConfigureApiServices(IServiceCollection services)
        {
            services.AddApiVersioning(options => options.VersionByQuery("api-version"));
            services.AddSwaggerApiVersioning(
                (version, info) =>
                {
                    info.Description =
                        "The Web API enabling access to the Maestro++ service that supports the [.NET Core Dependency Flow infrastructure](https://github.com/dotnet/arcade/blob/master/Documentation/DependenciesFlowPlan.md).";
                    info.Contact = new Contact
                    {
                        Name = ".NET Core Engineering",
                        Email = "dnceng@microsoft.com",
                    };
                });
            services.Configure<MvcJsonOptions>(
                options =>
                {
                    options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    options.SerializerSettings.Converters.Add(new StringEnumConverter {CamelCaseText = true});
                    options.SerializerSettings.Converters.Add(
                        new IsoDateTimeConverter
                        {
                            DateTimeFormat = "yyyy-MM-ddTHH:mm:ssZ",
                            DateTimeStyles = DateTimeStyles.AdjustToUniversal
                        });
                });

            services.AddSwaggerGen(
                options =>
                {
                    // If you get an exception saying 'Identical schemaIds detected for types Maestro.Web.Api.<version>.Models.<something> and Maestro.Web.Api.<different-version>.Models.<something>'
                    // Then you should NEVER add the following like the StackOverflow answers will suggest.
                    // options.CustomSchemaIds(x => x.FullName);

                    // This exception means that you have added something to one of the versions of the api that results in a conflict, because one version of the api cannot have 2 models for the same object
                    // e.g. If you add a new api, or just a new model to an existing version (with new or modified properties), every method in the API that can return this type,
                    // even nested (e.g. you changed Build, and Subscription contains a Build object), must be updated to return the new type.
                    // It could also mean that you forgot to apply [ApiRemoved] to an inherited method that shouldn't be included in the new version

                    var appJson = new[] {"application/json"}.ToList();
                    options.FilterOperations(
                        (op, ctx) =>
                        {
                            op.Responses["default"] = new Response
                            {
                                Description = "Error",
                                Schema = ctx.SchemaRegistry.GetOrRegister(typeof(ApiError))
                            };
                            // Replace the large list generated by WepApi with just application/json 
                            // We can accept more than just application/json, but the swagger spec defines what we prefer
                            op.Consumes = appJson;
                            op.Produces = appJson;
                            op.OperationId = $"{op.Tags.First()}_{op.OperationId}";
                        });

                    options.FilterOperations(
                        (op, ctx) =>
                        {
                            var paginated = ctx.MethodInfo.GetCustomAttribute<PaginatedAttribute>();
                            if (paginated != null)
                            {
                                // Add an extension that tells the client generator that this operation is paged with first,prev,next,last urls in the Link header.
                                op.Extensions["x-ms-paginated"] = new
                                {
                                    page = paginated.PageParameterName,
                                    pageSize = paginated.PageSizeParameterName
                                };
                            }
                        });

                    options.FilterSchemas(
                        (schema, ctx) =>
                        {
                            // Types that are not-nullable in C# should be required
                            if (ctx.JsonContract is JsonObjectContract contract)
                            {
                                var required = schema.Required == null
                                    ? new HashSet<string>()
                                    : new HashSet<string>(schema.Required);
                                foreach (var property in contract.Properties)
                                {
                                    var propertyType = property.PropertyType;
                                    var shouldBeRequired =
                                        propertyType.IsValueType &&
                                        !(propertyType.IsConstructedGenericType &&
                                          propertyType.GetGenericTypeDefinition() == typeof(Nullable<>));
                                    if (shouldBeRequired)
                                    {
                                        required.Add(property.PropertyName);
                                    }
                                }
                                schema.Required = required.ToList();
                            }
                        });

                    options.MapType<TimeSpan>(
                        () => new Schema
                        {
                            Type = "string",
                            Format = "duration"
                        });
                    options.MapType<TimeSpan?>(
                        () => new Schema
                        {
                            Type = "string",
                            Format = "duration"
                        });
                    options.MapType<JToken>(() => new Schema());

                    options.DescribeAllEnumsAsStrings();
                    options.SchemaRegistryOptions.UseReferencedDefinitionsForEnums = true;

                    string xmlPath;
                    if (HostingEnvironment.IsDevelopment())
                    {
                        xmlPath = Path.GetDirectoryName(typeof(Startup).Assembly.Location);
                    }
                    else
                    {
                        xmlPath = HostingEnvironment.ContentRootPath;
                    }

                    string xmlFile = Path.Combine(xmlPath, "Maestro.Web.xml");
                    if (File.Exists(xmlFile))
                    {
                        options.IncludeXmlComments(xmlFile);
                    }

                    options.AddSecurityDefinition(
                        "Bearer",
                        new ApiKeyScheme
                        {
                            Type = "apiKey",
                            In = "header",
                            Name = "Authorization"
                        });

                    options.FilterDocument(
                        (doc, ctx) =>
                        {
                            doc.Security = new List<IDictionary<string, IEnumerable<string>>>
                            {
                                new Dictionary<string, IEnumerable<string>>
                                {
                                    ["Bearer"] = Enumerable.Empty<string>()
                                }
                            };
                        });
                });
        }
    }
}
