parameters:
  Subscription: ''
  ServiceFabricConnection: ''
  PublishProfile: ''
  DotNetStatusAppName: ''
  DeploymentEnvironment: ''
  VariableGroup: ''
  MaestroPublishEndpoint: ''
  MaestroTestEndpoint: ''

  # --- Secret Variable group requirements ---
  # maestro-admin-sql-connection-string
  # scenario-test-maestro-token
  # dn-bot-dnceng-build-rw-code-rw-release-rw
  # maestro-scenario-test-github-token

stages:
- stage: deploy
  displayName: Deploy
  dependsOn:
  - build
  variables:
  - group: ${{ parameters.VariableGroup }}
  - name: PublishProfile
    value: ${{ parameters.PublishProfile }}
  - name: MaestroTestEndpoint
    value: ${{ parameters.MaestroTestEndpoint }}
  jobs:
  - deployment: approval
    displayName: deployment approval (conditional)
    environment: ${{ parameters.DeploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
  - job: updateDatabase
    dependsOn: 
    - approval
    displayName: Update BuildAssetRegistry database
    steps:
    - download: current
      artifact: ReleaseUtilities
    - download: current
      artifact: Maestro.Data
    - task: UseDotNet@2
      displayName: Use .NET 3.0.x SDK
      inputs:
        packageType: sdk
        version: 3.0.x
    - task: UseDotNet@2
      displayName: Use .NET 2.1.x runtime
      inputs:
        packageType: runtime
        version: 2.1.x
    - task: AzurePowerShell@3
      displayName: eng\firewall.ps1 -Add
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ScriptPath: $(Pipeline.Workspace)/ReleaseUtilities/firewall.ps1
        ScriptArguments: -RuleName UnblockSQLForUpgrade -Add -ConnectionString "$(maestro-admin-sql-connection-string)"
        azurePowerShellVersion: LatestVersion
    - task: PowerShell@2
      displayName: update-database.ps1
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/Maestro.Data/update-database.ps1
        arguments: Maestro.Data.dll
        workingDirectory: $(Pipeline.Workspace)/Maestro.Data
      env:
        BUILD_ASSET_REGISTRY_DB_CONNECTION_STRING: $(maestro-admin-sql-connection-string)
    - task: AzurePowerShell@3
      displayName: eng\firewall.ps1 -Remove
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ScriptPath: $(Pipeline.Workspace)/ReleaseUtilities/firewall.ps1
        ScriptArguments: -RuleName UnblockSQLForUpgrade -Remove -ConnectionString "$(maestro-admin-sql-connection-string)"
        azurePowerShellVersion: LatestVersion
      condition: always()

  - job: deployMaestro
    displayName: Deploy maestro service fabric application
    dependsOn: 
    - updateDatabase
    - approval
    steps:
    - download: current
      artifact: MaestroApplication
    - task: ServiceFabricDeploy@1
      displayName: Deploy Service Fabric Application (Maestro)
      inputs:
        applicationPackagePath: $(Pipeline.Workspace)/MaestroApplication/applicationpackage
        serviceConnectionName: ${{ parameters.ServiceFabricConnection }}
        publishProfilePath: $(Pipeline.Workspace)/MaestroApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        applicationParameterPath: $(Pipeline.Workspace)/MaestroApplication/projectartifacts/ApplicationParameters/$(PublishProfile).xml

  - job: deployTelemetry
    displayName: Deploy telemetry service fabric application
    dependsOn: 
    - approval
    steps:
    - download: current
      artifact: TelemetryApplication
    - task: ServiceFabricDeploy@1
      displayName: Deploy Service Fabric Application (Telemetry)
      inputs:
        applicationPackagePath: $(Pipeline.Workspace)/TelemetryApplication/applicationpackage
        serviceConnectionName: ${{ parameters.ServiceFabricConnection }}
        publishProfilePath: $(Pipeline.Workspace)/TelemetryApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        applicationParameterPath: $(Pipeline.Workspace)/TelemetryApplication/projectartifacts/ApplicationParameters/$(PublishProfile).xml

  - job: deployStatus
    displayName: Deploy dotnet-status web app
    dependsOn: 
    - approval
    steps:
    - download: current
      artifact: DotNetStatus
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: AzureRM
        azureSubscription: ${{ parameters.Subscription }}
        appType: webApp
        WebAppName: ${{ parameters.DotNetStatusAppName }}
        deployToSlotOrASE: true
        ResourceGroupName: monitoring
        SlotName: staging
        Package: $(Pipeline.Workspace)/DotNetStatus/DotNetStatus.zip
        enableCustomDeployment: true
        DeploymentType: webDeploy
        RemoveAdditionalFilesFlag: true

- stage: validateDeployment
  displayName: Validate deployment
  dependsOn: 
  - deploy
  variables:
  - group: ${{ parameters.VariableGroup }}
  jobs:
  - job: scenario
    displayName: Scenario tests
    steps:
    - download: current
      artifact: ScenarioTests
    - download: current
      artifact: PackageArtifacts
    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x
    - powershell: |
        nuget sources add -Name "arcade" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-tools-internal/index.json"
        nuget sources add -Name "dotnet-core" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json"
      displayName: Add nuget Sources
    - powershell: |
        $versionEndpoint = "$(MaestroTestEndpoint)/api/assets/darc-version?api-version=2019-01-16"
        $latestDarcVersion = $darcVersion = $(Invoke-WebRequest -Uri $versionEndpoint -UseBasicParsing).Content
        Write-Host "##vso[task.setvariable variable=darcVersion]$latestDarcVersion"
        Write-Host "Using Darc version $latestDarcVersion to run the tests"
      displayName: Get DARC version
    - task: PowerShell@2
      displayName: Run Scenario Tests
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/ScenarioTests/all.ps1
        arguments: -maestroInstallation "$(MaestroTestEndpoint)" -darcVersion "$(darcVersion)" -maestroBearerToken "$(scenario-test-maestro-token)" -githubPAT "$(maestro-scenario-test-github-token)" -azdoPAT "$(dn-bot-dnceng-build-rw-code-rw-release-rw)" -darcPackageSource "$(Pipeline.Workspace)\PackageArtifacts"
        workingDirectory: $(Pipeline.Workspace)/ScenarioTests
      timeoutInMinutes: 90

- stage: deployDarc
  displayName: Deploy DARC
  dependsOn:
  - validateDeployment
  variables:
  - name: MaestroPublishEndpoint
    value: ${{ parameters.MaestroPublishEndpoint }}
  jobs:
  - job: darc
    steps:
    - download: current
      artifact: AssetManifests
    - task: PowerShell@2
      displayName: Move build to channel
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/_cibuild/ReleaseUtilities/update-channel.ps1
        arguments: -maestroEndpoint "$(MaestroPublishEndpoint)" -barToken "$(MaestroAccessToken)" -targetChannel "$(TargetChannel)" -assetManifestPath "$(Pipeline.Workspace)/AssetManifests/Windows_NT-AnyCPU.xml"
