parameters:
  Subscription: ''
  ServiceFabricConnection: ''
  PublishProfile: ''
  DotNetStatusAppName: ''
  DeploymentEnvironment: ''
  VariableGroup: ''
  MaestroPublishEndpoint: ''
  MaestroTestEndpoint: ''
  DotNetStatusEndpoint: ''
  StatusVariableGroup: ''

  # --- Secret Variable group requirements ---
  # maestro-admin-sql-connection-string
  # scenario-test-maestro-token
  # dn-bot-dnceng-build-rw-code-rw-release-rw
  # maestro-scenario-test-github-token
  # dotnet-build-bot-dotnet-eng-status-token

stages:
- stage: predeploy
  displayName: Pre-Deployment
  pool:
    name: Hosted VS2017
  jobs:
  - job: notifyStartDeployment
    displayName: Notify deployment start
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/start
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /arcade-services/$(Build.BuildNumber)/start

- stage: deploy
  displayName: Deploy
  pool:
    name: Hosted VS2017
  dependsOn:
  - predeploy
  variables:
  - group: ${{ parameters.VariableGroup }}
  - name: PublishProfile
    value: ${{ parameters.PublishProfile }}
  jobs:
  - deployment: approval
    displayName: deployment approval (conditional)
    environment: ${{ parameters.DeploymentEnvironment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
  - job: updateDatabase
    dependsOn: 
    - approval
    displayName: Update BuildAssetRegistry database
    steps:
    - download: Build
      artifact: ReleaseUtilities
    - download: Build
      artifact: Maestro.Data
    - task: UseDotNet@2
      displayName: Use .NET 3.0.x SDK
      inputs:
        packageType: sdk
        version: 3.0.x
    - task: UseDotNet@2
      displayName: Use .NET 2.1.x runtime
      inputs:
        packageType: runtime
        version: 2.1.x
    - task: AzurePowerShell@3
      displayName: eng\firewall.ps1 -Add
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ScriptPath: $(Pipeline.Workspace)/Build/ReleaseUtilities/firewall.ps1
        ScriptArguments: -RuleName UnblockSQLForUpgrade -Add -ConnectionString "$(maestro-admin-sql-connection-string)"
        azurePowerShellVersion: LatestVersion
    - task: PowerShell@2
      displayName: update-database.ps1
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/Build/Maestro.Data/update-database.ps1
        arguments: Maestro.Data.dll
        workingDirectory: $(Pipeline.Workspace)/Build/Maestro.Data
      env:
        BUILD_ASSET_REGISTRY_DB_CONNECTION_STRING: $(maestro-admin-sql-connection-string)
    - task: AzurePowerShell@3
      displayName: eng\firewall.ps1 -Remove
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ScriptPath: $(Pipeline.Workspace)/Build/ReleaseUtilities/firewall.ps1
        ScriptArguments: -RuleName UnblockSQLForUpgrade -Remove -ConnectionString "$(maestro-admin-sql-connection-string)"
        azurePowerShellVersion: LatestVersion
      condition: always()

  - job: deployMaestro
    displayName: Deploy maestro service fabric application
    dependsOn: 
    - updateDatabase
    - approval
    steps:
    - download: Build
      artifact: MaestroApplication
    - task: ServiceFabricDeploy@1
      displayName: Deploy Service Fabric Application (Maestro)
      inputs:
        applicationPackagePath: $(Pipeline.Workspace)/Build/MaestroApplication/applicationpackage
        serviceConnectionName: ${{ parameters.ServiceFabricConnection }}
        publishProfilePath: $(Pipeline.Workspace)/Build/MaestroApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        applicationParameterPath: $(Pipeline.Workspace)/Build/MaestroApplication/projectartifacts/ApplicationParameters/$(PublishProfile).xml

  - job: deployTelemetry
    displayName: Deploy telemetry service fabric application
    dependsOn: 
    - approval
    steps:
    - download: Build
      artifact: TelemetryApplication
    - task: ServiceFabricDeploy@1
      displayName: Deploy Service Fabric Application (Telemetry)
      inputs:
        applicationPackagePath: $(Pipeline.Workspace)/Build/TelemetryApplication/applicationpackage
        serviceConnectionName: ${{ parameters.ServiceFabricConnection }}
        publishProfilePath: $(Pipeline.Workspace)/Build/TelemetryApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        applicationParameterPath: $(Pipeline.Workspace)/Build/TelemetryApplication/projectartifacts/ApplicationParameters/$(PublishProfile).xml

  - job: deployStatus
    displayName: Deploy dotnet-status web app
    dependsOn: 
    - approval
    steps:
    - download: Build
      artifact: DotNetStatus
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: AzureRM
        azureSubscription: ${{ parameters.Subscription }}
        appType: webApp
        WebAppName: ${{ parameters.DotNetStatusAppName }}
        deployToSlotOrASE: true
        ResourceGroupName: monitoring
        SlotName: staging
        Package: $(Pipeline.Workspace)/Build/DotNetStatus/DotNetStatus.zip
        enableCustomDeployment: true
        DeploymentType: webDeploy
        RemoveAdditionalFilesFlag: true
  
  - job: deployRolloutScorer
    displayName: Deploy rollout scorer azure function
    dependsOn: 
    - approval
    steps:
    - download: Build
      artifact: RolloutScorer
    - task: AzureFunctionApp@1
      displayName: Deploy RolloutScorer
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ${{ if ne(parameters.DeploymentEnvironment, 'Production') }}:
          appSettings: >
            -AzureServicesAuthConnectionString "RunAs=App;AppId=7d568741-c2b9-40a3-bbcc-9c3e82c3d872"
            -DeploymentEnvironment Staging
            -ScorecardsStorageAccountKeySecretName "rolloutscorecardsstaging-storage-key"
            -ScorecardsStorageAccountName "rolloutscorecardsstaging"
            -ScorecardsStorageAccountTableName "scorecardsstaging"
        ${{ if eq(parameters.DeploymentEnvironment, 'Production') }}:
          appSettings: >
            -AzureServicesAuthConnectionString "RunAs=App;AppId=7d568741-c2b9-40a3-bbcc-9c3e82c3d872"
            -DeploymentEnvironment Production
            -ScorecardsStorageAccountKeySecretName "rolloutscorecards-storage-key"
            -ScorecardsStorageAccountName "rolloutscorecards"
            -ScorecardsStorageAccountTableName "scorecards"
        package: $(Pipeline.Workspace)/Build/RolloutScorer/RolloutScorer.zip
        appName: ${{ parameters.RolloutScorerAppName }}

- stage: postdeploy
  displayName: Post-Deployment
  pool:
    name: Hosted VS2017
  dependsOn:
  - deploy
  condition: always()
  variables:
  - group: ${{ parameters.StatusVariableGroup }}
  - group: ${{ parameters.VariableGroup }}
  - group: ${{ parameters.GrafanaVariableGroup }}
  - name: DeploymentEnvironment
    value: ${{ parameters.DeploymentEnvironment }}
  - name: GrafanaHost
    value: ${{ parameters.GrafanaHost }}
  - name: GrafanaKeyVault
    value: ${{ parameters.GrafanaKeyVault }}
  jobs:
  - job: notifyEndDeployment
    displayName: Notify deployment end
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/end
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /arcade-services/$(Build.BuildNumber)/end
  - job: updateMetrics
    displayName: Update Grafana Metrics
    dependsOn:
    steps:
    - script: dotnet publish $(Build.SourcesDirectory)\src\Monitoring\Sdk\Microsoft.DotNet.Monitoring.Sdk.csproj -f netcoreapp2.1
    - script: dotnet build $(Build.SourcesDirectory)\src\Monitoring\Monitoring.ArcadeServices\Monitoring.ArcadeServices.proj -t:PublishGrafana -p:GrafanaAccessToken=$(grafana-admin-api-key) -p:GrafanaHost=$(GrafanaHost) -p:GrafanaKeyVaultName=$(GrafanaKeyVault) -p:GrafanaKeyVaultAppId=2bdfceef-194a-4775-99d9-b5575c77bc6b -p:GrafanaKeyVaultAppSecret=$(key-vault-app-secret) -p:GrafanaEnvironment=$(DeploymentEnvironment) -v:normal

- stage: validateDeployment
  displayName: Validate deployment
  pool:
    vmImage: vs2017-win2016
  dependsOn: 
  - deploy
  variables:
  - group: ${{ parameters.VariableGroup }}
  - name: MaestroTestEndpoint
    value: ${{ parameters.MaestroTestEndpoint }}
  jobs:
  - job: scenario
    displayName: Scenario tests
    steps:
    - download: Build
      artifact: ScenarioTests
    - download: Build
      artifact: PackageArtifacts
    - download: Build
      artifact: Maestro.ScenarioTests

    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x

    - task: UseDotNet@2
      displayName: Use .NET Core Sdk (3.0.101)
      inputs:
        packageType: sdk
        version: 3.0.101

    - task: UseDotNet@2
      displayName: Use .NET Core Sdk (2.1.803)
      inputs:
        packageType: sdk
        version: 2.1.803

    - task: VSTest@2
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: |
          Maestro.ScenarioTests.dll
        searchFolder: $(Pipeline.Workspace)/Build/Maestro.ScenarioTests
      env:
        MAESTRO_BASEURI: $(MaestroTestEndpoint)
        MAESTRO_TOKEN: $(scenario-test-maestro-token)
        GITHUB_TOKEN: $(maestro-scenario-test-github-token)
        DARC_PACKAGE_SOURCE: $(Pipeline.Workspace)\Build\PackageArtifacts

    - powershell: |
        nuget sources add -Name "arcade" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-tools-internal/index.json"
        nuget sources add -Name "dotnet-core" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json"
      displayName: Add nuget Sources
    - powershell: |
        $versionEndpoint = "$(MaestroTestEndpoint)/api/assets/darc-version?api-version=2019-01-16"
        $latestDarcVersion = $darcVersion = $(Invoke-WebRequest -Uri $versionEndpoint -UseBasicParsing).Content
        Write-Host "##vso[task.setvariable variable=darcVersion]$latestDarcVersion"
        Write-Host "Using Darc version $latestDarcVersion to run the tests"
      displayName: Get DARC version

    - task: PowerShell@2
      displayName: Run Scenario Tests
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/Build/ScenarioTests/all.ps1
        arguments: -maestroInstallation "$(MaestroTestEndpoint)" -darcVersion "$(darcVersion)" -maestroBearerToken "$(scenario-test-maestro-token)" -githubPAT "$(maestro-scenario-test-github-token)" -azdoPAT "$(dn-bot-dnceng-build-rw-code-rw-release-rw)" -darcPackageSource "$(Pipeline.Workspace)\Build\PackageArtifacts"
        workingDirectory: $(Pipeline.Workspace)/Build/ScenarioTests
      timeoutInMinutes: 90


    
