parameters:
  Subscription: ''
  ServiceFabricConnection: ''
  PublishProfile: ''
  DotNetStatusAppName: ''
  DeploymentEnvironment: ''
  VariableGroup: ''
  MaestroPublishEndpoint: ''
  MaestroTestEndpoint: ''
  DotNetStatusEndpoint: ''
  StatusVariableGroup: ''

  # --- Secret Variable group requirements ---
  # build-asset-registry-admin-connection-string
  # scenario-test-maestro-token
  # dn-bot-dnceng-build-rw-code-rw-release-rw
  # maestro-scenario-test-github-token
  # dotnet-build-bot-dotnet-eng-status-token
  # secret-manager-scenario-tests-client-secret

stages:
- stage: ValidateSecrets
  dependsOn:
  - build
  jobs:
  - job: ValidateSecrets
    pool: 
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    - task: UseDotNet@2
      displayName: Install Correct .NET Version
      inputs:
        useGlobalJson: true

    - script: dotnet build
      workingDirectory: src/Microsoft.DncEng.SecretManager

    - task: AzureCLI@2
      inputs:
        azureSubscription: DotNet Eng Services Secret Manager
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          Get-ChildItem .vault-config/*.yaml |% { dotnet run -p src/Microsoft.DncEng.SecretManager -- synchronize --verify-only $_}

- stage: approval
  pool: server
  dependsOn:
  - build
  - Validate
  - ValidateSecrets
  jobs:
  - deployment: approval
    displayName: deployment approval (conditional)
    environment: ${{ parameters.DeploymentEnvironment }}

- stage: predeploy
  displayName: Pre-Deployment
  pool: server
  dependsOn:
  - build
  - Validate
  - approval
  jobs:
  - job: notifyStartDeployment
    displayName: Notify deployment start
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/start
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /arcade-services/$(Build.BuildNumber)/start

- stage: deploy
  displayName: Deploy
  pool:
    name: NetCore1ESPool-Internal-NoMSI
    demands: ImageOverride -equals 1es-windows-2019
  dependsOn:
  - predeploy
  - approval
  variables:
  - group: ${{ parameters.VariableGroup }}
  - name: PublishProfile
    value: ${{ parameters.PublishProfile }}
  jobs:
  - job: updateDatabase
    displayName: Update BuildAssetRegistry database
    steps:
    - download: current
      artifact: ReleaseUtilities
    - download: current
      artifact: Maestro.Data

    - task: UseDotNet@2
      displayName: Install Correct .NET Version
      inputs:
        useGlobalJson: true

    - task: AzurePowerShell@3
      displayName: eng\firewall.ps1 -Add
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ScriptPath: $(Pipeline.Workspace)/ReleaseUtilities/firewall.ps1
        ScriptArguments: -RuleName UnblockSQLForUpgrade -Add -ConnectionString "$(build-asset-registry-admin-connection-string)"
        azurePowerShellVersion: LatestVersion
    - task: PowerShell@2
      displayName: update-database.ps1
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/Maestro.Data/update-database.ps1
        arguments: Maestro.Data.dll
        workingDirectory: $(Pipeline.Workspace)/Maestro.Data
      env:
        BUILD_ASSET_REGISTRY_DB_CONNECTION_STRING: $(build-asset-registry-admin-connection-string)
    - task: AzurePowerShell@3
      displayName: eng\firewall.ps1 -Remove
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ScriptPath: $(Pipeline.Workspace)/ReleaseUtilities/firewall.ps1
        ScriptArguments: -RuleName UnblockSQLForUpgrade -Remove -ConnectionString "$(build-asset-registry-admin-connection-string)"
        azurePowerShellVersion: LatestVersion
      condition: always()

  - job: deployMaestro
    displayName: Deploy maestro service fabric application
    dependsOn:
    - updateDatabase
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    - download: current
      artifact: MaestroApplication
    - download: current
      artifact: ReleaseUtilities
    - task: AzurePowerShell@5
      displayName: Deploy Service Fabric Application (Maestro)
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        scriptType: inlineScript
        azurePowerShellVersion: LatestVersion
        inline: |
          $autoRollBack = $true
          if ($env:DisableAutoRollBack -eq 'true') {
            $autoRollBack = $false
          }
          if ($env:BUILD_SOURCEBRANCH -eq 'refs/heads/main') {
            $autoRollBack = $false
          }
          eng/deployment/deploy.ps1 -obj $env:BUILD_ARTIFACTSTAGINGDIRECTORY -appPackagePath $env:ApplicationPackage -publishProfile $env:PublishProfilePath -autoRollBack $autoRollBack -location westus2
      env:
        PublishProfilePath: $(Pipeline.Workspace)/MaestroApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        ApplicationPackage: $(Pipeline.Workspace)/MaestroApplication/applicationpackage

  - job: deployTelemetry
    displayName: Deploy telemetry service fabric application
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019    
    dependsOn:
    steps:
    - download: current
      artifact: TelemetryApplication
    - download: current
      artifact: ReleaseUtilities
    - task: AzurePowerShell@5
      displayName: Deploy Service Fabric Application (Telemetry)
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        scriptType: inlineScript
        azurePowerShellVersion: LatestVersion
        inline: |
          $autoRollBack = $true
          if ($env:DisableAutoRollBack -eq 'true') {
            $autoRollBack = $false
          }
          if ($env:BUILD_SOURCEBRANCH -eq 'refs/heads/main') {
            $autoRollBack = $false
          }
          eng/deployment/deploy.ps1 -obj $env:BUILD_ARTIFACTSTAGINGDIRECTORY -appPackagePath $env:ApplicationPackage -publishProfile $env:PublishProfilePath -autoRollBack $autoRollBack -location westus2
      env:
        PublishProfilePath: $(Pipeline.Workspace)/TelemetryApplication/projectartifacts/PublishProfiles/$(PublishProfile).xml
        ApplicationPackage: $(Pipeline.Workspace)/TelemetryApplication/applicationpackage

  - job: deployStatus
    displayName: Deploy dotnet-status web app
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    dependsOn:
    steps:
    - download: current
      artifact: DotNetStatus
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: AzureRM
        azureSubscription: ${{ parameters.Subscription }}
        appType: webApp
        WebAppName: ${{ parameters.DotNetStatusAppName }}
        deployToSlotOrASE: true
        ResourceGroupName: monitoring
        SlotName: staging
        Package: $(Pipeline.Workspace)/DotNetStatus/DotNetStatus.zip
        enableCustomDeployment: true
        DeploymentType: webDeploy
        RemoveAdditionalFilesFlag: true

  - job: deployRolloutScorer
    displayName: Deploy rollout scorer azure function
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    dependsOn:
    steps:
    - download: current
      artifact: RolloutScorer
    - task: AzureFunctionApp@1
      displayName: Deploy RolloutScorer
      inputs:
        azureSubscription: ${{ parameters.Subscription }}
        ${{ if ne(parameters.DeploymentEnvironment, 'Production') }}:
          appSettings: >
            -AzureServicesAuthConnectionString "RunAs=App;AppId=7d568741-c2b9-40a3-bbcc-9c3e82c3d872"
            -DeploymentEnvironment Staging
            -ScorecardsStorageAccountKeySecretName "rolloutscorecardsstaging-storage-key"
            -ScorecardsStorageAccountName "rolloutscorecardsstaging"
            -ScorecardsStorageAccountTableName "scorecardsstaging"
        ${{ if eq(parameters.DeploymentEnvironment, 'Production') }}:
          appSettings: >
            -AzureServicesAuthConnectionString "RunAs=App;AppId=7d568741-c2b9-40a3-bbcc-9c3e82c3d872"
            -DeploymentEnvironment Production
            -ScorecardsStorageAccountKeySecretName "rolloutscorecards-storage-key"
            -ScorecardsStorageAccountName "rolloutscorecards"
            -ScorecardsStorageAccountTableName "scorecards"
        package: $(Pipeline.Workspace)/RolloutScorer/RolloutScorer.zip
        appName: ${{ parameters.RolloutScorerAppName }}

- stage: postdeploy
  displayName: Post-Deployment
  pool:
    name: NetCore1ESPool-Internal-NoMSI
    demands: ImageOverride -equals 1es-windows-2019
  dependsOn:
  - deploy
  variables:
  - group: ${{ parameters.StatusVariableGroup }}
  - group: ${{ parameters.VariableGroup }}
  - group: ${{ parameters.GrafanaVariableGroup }}
  - name: DeploymentEnvironment
    value: ${{ parameters.DeploymentEnvironment }}
  - name: GrafanaHost
    value: ${{ parameters.GrafanaHost }}
  - name: GrafanaKeyVault
    value: ${{ parameters.GrafanaKeyVault }}
  jobs:
  - job: notifyEndDeployment
    displayName: Notify deployment end
    condition: always()
    pool: server
    steps:
    - task: InvokeRESTAPI@1
      displayName: Notify dotnet-eng-status/end
      continueOnError: true
      inputs:
        serviceConnection: ${{ parameters.DotNetStatusEndpoint }}
        method: POST
        urlSuffix: /arcade-services/$(Build.BuildNumber)/end
  - job: updateMetrics
    displayName: Update Grafana Metrics
    dependsOn:
    steps:
    - task: UseDotNet@2
      displayName: Install Correct .NET Version
      inputs:
        useGlobalJson: true
    - script: dotnet publish $(Build.SourcesDirectory)\src\Monitoring\Sdk\Microsoft.DotNet.Monitoring.Sdk.csproj -f net6.0
    - script: dotnet build $(Build.SourcesDirectory)\src\Monitoring\Monitoring.ArcadeServices\Monitoring.ArcadeServices.proj -t:PublishGrafana -p:GrafanaAccessToken=$(grafana-admin-api-key) -p:GrafanaHost=$(GrafanaHost) -p:GrafanaKeyVaultName=$(GrafanaKeyVault) -p:GrafanaKeyVaultAppId=$(engineering-services-app-id) -p:GrafanaKeyVaultAppSecret=$(engineering-services-app-secret) -p:GrafanaEnvironment=$(DeploymentEnvironment) -p:ParametersFile=parameters.json -v:normal

- stage: validateDeployment
  displayName: Validate deployment
  pool:
    name: NetCore1ESPool-Internal
    demands: ImageOverride -equals 1es-windows-2019
  dependsOn:
  - deploy
  variables:
  - group: ${{ parameters.VariableGroup }}
  # Secret-Manager-Scenario-Tests provides: secret-manager-scenario-tests-client-secret
  - group: Secret-Manager-Scenario-Tests
  - name: MaestroTestEndpoint
    value: ${{ parameters.MaestroTestEndpoint }}
  jobs:
  - job: scenario
    displayName: Scenario tests
    timeoutInMinutes: 90
    steps:
    - download: current
      artifact: PackageArtifacts
    - download: current
      artifact: Microsoft.DncEng.SecretManager.ScenarioTests
    - download: current
      artifact: Maestro.ScenarioTests

    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x

    - task: UseDotNet@2
      displayName: Install Correct .NET Version
      inputs:
        useGlobalJson: true

    - task: VSTest@2
      displayName: Secret Manager Scenario Tests
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: |
          Microsoft.DncEng.SecretManager.ScenarioTests.dll
        searchFolder: $(Pipeline.Workspace)/Microsoft.DncEng.SecretManager.ScenarioTests
      env:
        AzureServicesAuthConnectionString: $(secret-manager-scenario-tests-client-secret)

    - task: VSTest@2
      displayName: Maestro Scenario Tests
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: |
          Maestro.ScenarioTests.dll
        searchFolder: $(Pipeline.Workspace)/Maestro.ScenarioTests
      env:
        MAESTRO_BASEURI: $(MaestroTestEndpoint)
        MAESTRO_TOKEN: $(scenario-test-maestro-token)
        GITHUB_TOKEN: $(maestro-scenario-test-github-token)
        AZDO_TOKEN: $(dn-bot-dnceng-build-rw-code-rw-release-rw)
        DARC_PACKAGE_SOURCE: $(Pipeline.Workspace)\PackageArtifacts

    - powershell: |
        nuget sources add -Name "arcade" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-tools-internal/index.json"
        nuget sources add -Name "dotnet-core" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json"
      displayName: Add nuget Sources
    - powershell: |
        $versionEndpoint = "$(MaestroTestEndpoint)/api/assets/darc-version?api-version=2019-01-16"
        $latestDarcVersion = $darcVersion = $(Invoke-WebRequest -Uri $versionEndpoint -UseBasicParsing).Content
        Write-Host "##vso[task.setvariable variable=darcVersion]$latestDarcVersion"
        Write-Host "Using Darc version $latestDarcVersion to run the tests"
      displayName: Get DARC version



