parameters:
  Subscription: ''
  ServiceFabricConnection: ''
  PublishProfile: ''
  DotNetStatusAppName: ''
  DeploymentEnvironment: ''
  VariableGroup: ''
  MaestroPublishEndpoint: ''
  MaestroTestEndpoint: ''
  DotNetStatusEndpoint: ''
  StatusVariableGroup: ''
  DarcBotVariableGroup: ''

  # --- Secret Variable group requirements ---
  # maestro-admin-sql-connection-string
  # scenario-test-maestro-token
  # dn-bot-dnceng-build-rw-code-rw-release-rw
  # maestro-scenario-test-github-token
  # dotnet-build-bot-dotnet-eng-status-token
  
stages:
- stage: validateDeployment
  displayName: Validate deployment
  pool:
    vmImage: vs2017-win2016
  variables:
  - group: ${{ parameters.VariableGroup }}
  - name: MaestroTestEndpoint
    value: ${{ parameters.MaestroTestEndpoint }}
  jobs:
  - job: scenario
    displayName: Scenario tests
    steps:
    - download: current
      artifact: ScenarioTests
    - download: current
      artifact: PackageArtifacts
    - download: current
      artifact: Maestro.ScenarioTests

    - task: NuGetToolInstaller@1
      displayName: Use NuGet
      inputs:
        versionSpec: 5.3.x

    - task: UseDotNet@2
      displayName: Use .NET Core Sdk
      inputs:
        packageType: sdk
        version: 3.1.x

    - task: VSTest@2
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: |
          Maestro.ScenarioTests.dll
        searchFolder: $(Pipeline.Workspace)/Maestro.ScenarioTests
      env:
        MAESTRO_BASEURI: $(MaestroTestEndpoint)
        MAESTRO_TOKEN: $(scenario-test-maestro-token)
        GITHUB_TOKEN: $(maestro-scenario-test-github-token)
        DARC_PACKAGE_SOURCE: $(Pipeline.Workspace)\PackageArtifacts

    - powershell: |
        nuget sources add -Name "arcade" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-tools-internal/index.json"
        nuget sources add -Name "dotnet-core" -Source "https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json"
      displayName: Add nuget Sources
    - powershell: |
        $versionEndpoint = "$(MaestroTestEndpoint)/api/assets/darc-version?api-version=2019-01-16"
        $latestDarcVersion = $darcVersion = $(Invoke-WebRequest -Uri $versionEndpoint -UseBasicParsing).Content
        Write-Host "##vso[task.setvariable variable=darcVersion]$latestDarcVersion"
        Write-Host "Using Darc version $latestDarcVersion to run the tests"
      displayName: Get DARC version

    - task: PowerShell@2
      displayName: Run Scenario Tests
      inputs:
        targetType: filePath
        filePath: $(Pipeline.Workspace)/ScenarioTests/all.ps1
        arguments: -maestroInstallation "$(MaestroTestEndpoint)" -darcVersion "$(darcVersion)" -maestroBearerToken "$(scenario-test-maestro-token)" -githubPAT "$(maestro-scenario-test-github-token)" -azdoPAT "$(dn-bot-dnceng-build-rw-code-rw-release-rw)" -darcPackageSource "$(Pipeline.Workspace)\PackageArtifacts"
        workingDirectory: $(Pipeline.Workspace)/ScenarioTests
      timeoutInMinutes: 90


    
