parameters:
  AzureSubscription: ''
  PublishProfile: ''
  stageName: 'Pre_Deploy_Tests'

stages:
- stage: ${{ parameters.stageName }}
  displayName: Pre-Deployment Validation
  pool:
    name: NetCore1ESPool-Internal-NoMSI
    demands: ImageOverride -equals 1es-windows-2019
  dependsOn:
  - Build
  jobs:
  - job: Validate_Existing_Services
    pool:
      name: NetCore1ESPool-Internal-NoMSI
      demands: ImageOverride -equals 1es-windows-2019
    steps:
    - download: current
      artifact: ValidationScripts
    - download: current
      artifact: ServiceFabricPublishProfiles
    - download: current
      artifact: ReleaseUtilities # for Publish profile parsing helper code
    - task: AzureCLI@2
      displayName: Validate Service Fabric Applications
      inputs:
        azureSubscription: ${{ parameters.AzureSubscription }}
        scriptType: ps
        scriptPath: $(Pipeline.Workspace)/ValidationScripts/Pre-DeployCheckServiceFabric.ps1
        arguments: '-PublishProfile "$(Pipeline.Workspace)/ServiceFabricPublishProfiles/${{ parameters.PublishProfile }}.xml"'
