// <auto-generated />
using System;
using Maestro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maestro.Data.Migrations
{
    [DbContext(typeof(BuildAssetRegistryContext))]
    [Migration("20220427230202_initial-squashed")]
    partial class initialsquashed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Maestro.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Maestro.Data.ApplicationUserPersonalAccessToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId", "Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("AspNetUserPersonalAccessTokens");
                });

            modelBuilder.Entity("Maestro.Data.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("NonShipping")
                        .HasColumnType("bit");

                    b.Property<string>("Version")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("Name", "Version");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Maestro.Data.Models.AssetLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetLocations");
                });

            modelBuilder.Entity("Maestro.Data.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AzureDevOpsAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AzureDevOpsBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AzureDevOpsBuildDefinitionId")
                        .HasColumnType("int");

                    b.Property<int?>("AzureDevOpsBuildId")
                        .HasColumnType("int");

                    b.Property<string>("AzureDevOpsBuildNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AzureDevOpsProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AzureDevOpsRepository")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateProduced")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GitHubBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHubRepository")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Released")
                        .HasColumnType("bit");

                    b.Property<bool>("Stable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("Maestro.Data.Models.BuildChannel", b =>
                {
                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateTimeAdded")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("BuildId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("BuildChannels");
                });

            modelBuilder.Entity("Maestro.Data.Models.BuildDependency", b =>
                {
                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int>("DependentBuildId")
                        .HasColumnType("int");

                    b.Property<bool>("IsProduct")
                        .HasColumnType("bit");

                    b.Property<double>("TimeToInclusionInMinutes")
                        .HasColumnType("float");

                    b.HasKey("BuildId", "DependentBuildId");

                    b.HasIndex("DependentBuildId");

                    b.ToTable("BuildDependencies");
                });

            modelBuilder.Entity("Maestro.Data.Models.BuildIncoherence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BuildId")
                        .HasColumnType("int");

                    b.Property<string>("Commit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repository")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("BuildIncoherencies");
                });

            modelBuilder.Entity("Maestro.Data.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Maestro.Data.Models.DefaultChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Repository", "Branch", "ChannelId")
                        .IsUnique();

                    b.ToTable("DefaultChannels");
                });

            modelBuilder.Entity("Maestro.Data.Models.DependencyFlowEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Event")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlowType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceRepository")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetRepository")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("DependencyFlowEvents");
                });

            modelBuilder.Entity("Maestro.Data.Models.GoalTime", b =>
                {
                    b.Property<int>("DefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.HasKey("DefinitionId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("GoalTime");
                });

            modelBuilder.Entity("Maestro.Data.Models.LongestBuildPath", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("BestCaseTimeInMinutes")
                        .HasColumnType("float");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("ContributingRepositories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ReportDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("WorstCaseTimeInMinutes")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("LongestBuildPaths");
                });

            modelBuilder.Entity("Maestro.Data.Models.Repository", b =>
                {
                    b.Property<string>("RepositoryName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint");

                    b.HasKey("RepositoryName");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Maestro.Data.Models.RepositoryBranch", b =>
                {
                    b.Property<string>("RepositoryName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PolicyString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Policy");

                    b.HasKey("RepositoryName", "BranchName");

                    b.ToTable("RepositoryBranches");
                });

            modelBuilder.Entity("Maestro.Data.Models.RepositoryBranchUpdate", b =>
                {
                    b.Property<string>("RepositoryName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arguments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime");

                    b.HasKey("RepositoryName", "BranchName");

                    b.ToTable("RepositoryBranchUpdates");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb.UseHistoryTable("RepositoryBranchUpdateHistory");
                            ttb
                                .HasPeriodStart("SysStartTime")
                                .HasColumnName("SysStartTime");
                            ttb
                                .HasPeriodEnd("SysEndTime")
                                .HasColumnName("SysEndTime");
                        }
                    ));
                });

            modelBuilder.Entity("Maestro.Data.Models.RepositoryBranchUpdateHistory", b =>
                {
                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arguments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SysEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysStartTime")
                        .HasColumnType("datetime2");

                    b.HasIndex("SysEndTime", "SysStartTime");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SysEndTime", "SysStartTime"));

                    b.HasIndex("RepositoryName", "BranchName", "SysEndTime", "SysStartTime");

                    b.ToTable("RepositoryBranchUpdateHistory", (string)null);
                });

            modelBuilder.Entity("Maestro.Data.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int?>("LastAppliedBuildId")
                        .HasColumnType("int");

                    b.Property<string>("PolicyString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Policy");

                    b.Property<string>("PullRequestFailureNotificationTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceRepository")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetRepository")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("LastAppliedBuildId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Maestro.Data.Models.SubscriptionUpdate", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arguments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SysEndTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime");

                    b.Property<DateTime>("SysStartTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime");

                    b.HasKey("SubscriptionId");

                    b.ToTable("SubscriptionUpdates");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb.UseHistoryTable("SubscriptionUpdateHistory");
                            ttb
                                .HasPeriodStart("SysStartTime")
                                .HasColumnName("SysStartTime");
                            ttb
                                .HasPeriodEnd("SysEndTime")
                                .HasColumnName("SysEndTime");
                        }
                    ));
                });

            modelBuilder.Entity("Maestro.Data.Models.SubscriptionUpdateHistory", b =>
                {
                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arguments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SysEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysStartTime")
                        .HasColumnType("datetime2");

                    b.HasIndex("SysEndTime", "SysStartTime");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("SysEndTime", "SysStartTime"));

                    b.HasIndex("SubscriptionId", "SysEndTime", "SysStartTime");

                    b.ToTable("SubscriptionUpdateHistory", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Maestro.Data.ApplicationUserPersonalAccessToken", b =>
                {
                    b.HasOne("Maestro.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("PersonalAccessTokens")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Maestro.Data.Models.Asset", b =>
                {
                    b.HasOne("Maestro.Data.Models.Build", null)
                        .WithMany("Assets")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maestro.Data.Models.AssetLocation", b =>
                {
                    b.HasOne("Maestro.Data.Models.Asset", null)
                        .WithMany("Locations")
                        .HasForeignKey("AssetId");
                });

            modelBuilder.Entity("Maestro.Data.Models.BuildChannel", b =>
                {
                    b.HasOne("Maestro.Data.Models.Build", "Build")
                        .WithMany("BuildChannels")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maestro.Data.Models.Channel", "Channel")
                        .WithMany("BuildChannels")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Maestro.Data.Models.BuildDependency", b =>
                {
                    b.HasOne("Maestro.Data.Models.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maestro.Data.Models.Build", "DependentBuild")
                        .WithMany()
                        .HasForeignKey("DependentBuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("DependentBuild");
                });

            modelBuilder.Entity("Maestro.Data.Models.BuildIncoherence", b =>
                {
                    b.HasOne("Maestro.Data.Models.Build", null)
                        .WithMany("Incoherencies")
                        .HasForeignKey("BuildId");
                });

            modelBuilder.Entity("Maestro.Data.Models.DefaultChannel", b =>
                {
                    b.HasOne("Maestro.Data.Models.Channel", "Channel")
                        .WithMany("DefaultChannels")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Maestro.Data.Models.DependencyFlowEvent", b =>
                {
                    b.HasOne("Maestro.Data.Models.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Maestro.Data.Models.GoalTime", b =>
                {
                    b.HasOne("Maestro.Data.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Maestro.Data.Models.LongestBuildPath", b =>
                {
                    b.HasOne("Maestro.Data.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Maestro.Data.Models.RepositoryBranch", b =>
                {
                    b.HasOne("Maestro.Data.Models.Repository", "Repository")
                        .WithMany("Branches")
                        .HasForeignKey("RepositoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Maestro.Data.Models.RepositoryBranchUpdate", b =>
                {
                    b.HasOne("Maestro.Data.Models.RepositoryBranch", "RepositoryBranch")
                        .WithOne()
                        .HasForeignKey("Maestro.Data.Models.RepositoryBranchUpdate", "RepositoryName", "BranchName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RepositoryBranch");
                });

            modelBuilder.Entity("Maestro.Data.Models.Subscription", b =>
                {
                    b.HasOne("Maestro.Data.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maestro.Data.Models.Build", "LastAppliedBuild")
                        .WithMany()
                        .HasForeignKey("LastAppliedBuildId");

                    b.Navigation("Channel");

                    b.Navigation("LastAppliedBuild");
                });

            modelBuilder.Entity("Maestro.Data.Models.SubscriptionUpdate", b =>
                {
                    b.HasOne("Maestro.Data.Models.Subscription", "Subscription")
                        .WithOne()
                        .HasForeignKey("Maestro.Data.Models.SubscriptionUpdate", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Maestro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Maestro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maestro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Maestro.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Maestro.Data.ApplicationUser", b =>
                {
                    b.Navigation("PersonalAccessTokens");
                });

            modelBuilder.Entity("Maestro.Data.Models.Asset", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Maestro.Data.Models.Build", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("BuildChannels");

                    b.Navigation("Incoherencies");
                });

            modelBuilder.Entity("Maestro.Data.Models.Channel", b =>
                {
                    b.Navigation("BuildChannels");

                    b.Navigation("DefaultChannels");
                });

            modelBuilder.Entity("Maestro.Data.Models.Repository", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
