<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Development.json"
             CopyToOutputDirectory="Never"
             CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.DotNet.ProductConstructionService.Client\Microsoft.DotNet.ProductConstructionService.Client.csproj" />
    <ProjectReference Include="..\ProductConstructionService.BarViz\ProductConstructionService.BarViz.csproj" />
  </ItemGroup>

</Project>
