variables:
- template: /eng/common/templates-official/variables/pool-providers.yml@self
- group: SDL_Settings
- name: _TeamName
  value: DotNetCore
- name: _PublishUsingPipelines
  value: true
- name: _DotNetArtifactsCategory
  value: .NETCore
- name: AzdoOrgUri
  value: https://dev.azure.com/dnceng
- name: AzdoProject
  value: internal
- name: resourceGroupName
  value: product-construction-service
- name: containerName
  value: product-construction-service.api

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/production') }}:
  - name: dockerRegistryUrl
    value: productconstructionprod.azurecr.io
  - name: containerRegistryName
    value: productconstructionprod
  - name: serviceConnectionName
    value: ProductConstructionServiceDeploymentProd
- ${{ else }}:
  - name: dockerRegistryUrl
    value: productconstructionint.azurecr.io
  - name: containerRegistryName
    value: productconstructionint
  - name: serviceConnectionName
    value: ProductConstructionServiceDeploymentInt
