parameters:
- name: configuration
  type: string
- name: buildArgs
  type: string
  default: ''
  
steps:
- task: NuGetToolInstaller@0
  displayName: Install NuGet
  inputs:
    versionSpec: 6.11.x

- powershell: |
    Write-Host "##vso[task.setvariable variable=VersionPrefix]1.1.0"
  displayName: Set Package Version

- powershell: |
    . .\eng\common\tools.ps1
    InitializeDotNetCli -install:$true
    .\.dotnet\dotnet workload update --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json
    .\.dotnet\dotnet workload install aspire --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json
  displayName: Install .NET and Aspire Workload

- script: >
    .\eng\common\cibuild.cmd
    -configuration ${{ parameters.configuration }}
    -prepareMachine
    /p:Test=false
    /p:Sign=false
    ${{ parameters.buildArgs }}
  displayName: Build
