parameters:
- name: configuration
  type: string
- name: buildArgs
  type: string
  default: ''
  
steps:
- task: NuGetToolInstaller@0
  displayName: Install NuGet
  inputs:
    versionSpec: 6.11.x

- powershell: |
    Write-Host "##vso[task.setvariable variable=VersionPrefix]1.1.0"
  displayName: Set Package Version

- script: >
    .\eng\common\cibuild.cmd
    -configuration ${{ parameters.configuration }}
    -prepareMachine
    /p:Test=false
    /p:Sign=false
    ${{ parameters.buildArgs }}
  displayName: Build
