storageLocation:
  type: azure-key-vault
  parameters:
    subscription: e6b5f9f5-0ca4-4351-879b-014d78400ec2
    name: ProductConstructionDev

secrets:

  github:
    type: github-app-secret
    parameters:
      hasPrivateKey: true
      hasWebhookSecret: false
      hasOAuthSecret: true