variables:
- name: dockerRegistryUrl
  value: productconstructionprod.azurecr.io
- name: containerRegistryName
  value: productconstructionprod
- name: pcsDeploymentServiceConnection
  value: ProductConstructionServiceDeploymentProd