// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Microsoft.DotNet.ProductConstructionService.Client.Models;
using Microsoft.DotNet.DarcLib.Models.Darc;
using NUnit.Framework;
using Microsoft.DotNet.DarcLib.Helpers;

#nullable enable
namespace ProductConstructionService.ScenarioTests;

[TestFixture]
[Category("PostDeployment")]
[Category("CodeFlow")]
internal partial class ScenarioTests_CodeFlow : CodeFlowScenarioTestBase
{
    private const string TestFile1Name = "newFile1.txt";
    private const string TestFile2Name = "newFile2.txt";
    private const string DefaultPatch = "@@ -0,0 +1 @@\n+test\n\\ No newline at end of file";
    private const string RepoSideDependencyCommit = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    private const string VmrSideDependencyCommit = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    private const string BuildDependencyInitialCommit = "cccccccccccccccccccccccccccccccccccccccc";

    private static string GetMaestroManagedFeedLocation(string repoName, string sha)
        => $"https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-{repoName}-{sha}/nuget/v3/index.json";

    private static readonly Dictionary<string, string> TestFilesContent = new()
    {
        { TestFile1Name, "test" },
        { TestFile2Name, "test" },
    };

    private static readonly Dictionary<string, string> TestFilePatches = new()
    {
        { $"{TestFile1Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo1Name}/{TestFile1Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo1Name}/{TestFile2Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo2Name}/{TestFile1Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo2Name}/{VersionFiles.VersionDetailsProps}", "@@ -0,0 +1,11 @@\n+<?xml version=\"1.0\" encoding=\"utf-8\"?>\n+<!--\n+This file is auto-generated by the Maestro dependency flow system.\n+Do not edit it manually, as it will get overwritten by automation.\n+This file should be imported by eng/Versions.props\n+-->\n+<Project>\n+  <PropertyGroup />\n+  <!--Property group for alternate package version names-->\n+  <PropertyGroup />\n+</Project>" }
    };


    [Test]
    public async Task Vmr_ForwardFlowTest()
    {
        var channelName = GetTestChannelName();
        var branchName = GetTestBranchName();
        var productRepo = GetGitHubRepoUrl(TestRepository.TestRepo1Name);
        var targetBranchName = GetTestBranchName();
        var testPrNumber = 23;

        await CreateTestChannelAsync(channelName);

        var subscriptionId = await CreateForwardFlowSubscriptionAsync(
            channelName,
            TestRepository.TestRepo1Name,
            TestRepository.VmrTestRepoName,
            targetBranchName,
            UpdateFrequency.None.ToString(),
            TestParameters.GitHubTestOrg,
            targetDirectory: TestRepository.TestRepo1Name,
            autoApprove: true);

        TemporaryDirectory vmrDirectory = await CloneRepositoryAsync(TestRepository.VmrTestRepoName);
        TemporaryDirectory reposFolder = await CloneRepositoryAsync(TestRepository.TestRepo1Name);
        var newFilePath = Path.Combine(reposFolder.Directory, TestFile1Name);

        await CreateTargetBranchAndExecuteTest(targetBranchName, vmrDirectory.Directory, async () =>
        {
            using (ChangeDirectory(reposFolder.Directory))
            {
                await using (await CheckoutBranchAsync(branchName))
                {
                    // Make a change in a product repo
                    TestContext.WriteLine("Making code changes to the repo");
                    await File.WriteAllTextAsync(newFilePath, TestFilesContent[TestFile1Name]);

                    await GitAddAllAsync();
                    await GitCommitAsync($"Change that would have been made in a pr (#{testPrNumber})");

                    // Push it to github
                    await using (await PushGitBranchAsync("origin", branchName))
                    {
                        var repoSha = (await GitGetCurrentSha()).TrimEnd();

                        // Create a new build from the commit and add it to a channel
                        Build build = await CreateBuildAsync(
                            GetGitHubRepoUrl(TestRepository.TestRepo1Name),
                            branchName,
                            repoSha,
                            "1",
                            []);

                        TestContext.WriteLine("Adding build to channel");
                        await AddBuildToChannelAsync(build.Id, channelName);

                        TestContext.WriteLine("Triggering the subscription");
                        // Now trigger the subscription
                        await TriggerSubscriptionAsync(subscriptionId);

                        TestContext.WriteLine("Verifying subscription PR");
                        var pr = await CheckForwardFlowGitHubPullRequest(
                            [(TestRepository.TestRepo1Name, repoSha)],
                            TestRepository.VmrTestRepoName,
                            targetBranchName,
                            [$"src/{TestRepository.TestRepo1Name}/{TestFile1Name}"],
                            TestFilePatches,
                            cleanUp: false);

                        await CheckIfPullRequestCommentExists(
                            TestRepository.VmrTestRepoName,
                            pr,
                            [$"https://github.com/maestro-auth-test/maestro-test1/pull/{testPrNumber}"]);

                        await WaitForPullRequestApprovalAsync(TestRepository.VmrTestRepoName, pr);
                    }
                }
            }
        });
    }

    [Test]
    public async Task Vmr_BackwardFlowTest()
    {
        var channelName = GetTestChannelName();
        var branchName = GetTestBranchName();
        var productRepo = GetGitHubRepoUrl(TestRepository.TestRepo2Name);
        var targetBranchName = GetTestBranchName();
        var includedPrNumber = 24;
        var excludedPrNumber = 25;

        await CreateTestChannelAsync(channelName);

        var subscriptionId = await CreateBackwardFlowSubscriptionAsync(
            channelName,
            TestRepository.VmrTestRepoName,
            TestRepository.TestRepo2Name,
            targetBranchName,
            UpdateFrequency.None.ToString(),
            TestParameters.GitHubTestOrg,
            sourceDirectory: TestRepository.TestRepo2Name);

        string repoSidePackage = GetUniqueAssetName("RepoSide");
        string vmrSidePackage = GetUniqueAssetName("VmrSide");
        string buildPackage = GetUniqueAssetName("Build");
        string pinnedArcade = DependencyFileManager.ArcadeSdkPackageName;
        string pinnedPackage = GetUniqueAssetName("Pinned");

        string repoSidePackageLocation = GetMaestroManagedFeedLocation("repo-side", RepoSideDependencyCommit);
        string vmrSidePackageLocation = GetMaestroManagedFeedLocation("vmr-side", VmrSideDependencyCommit);
        string buildPackageLocation = GetMaestroManagedFeedLocation("build-update", "dddddddddddddddddddddddddddddddddddddddd");

        List<AssetData> repoSideAssets = [GetAssetDataWithLocations(repoSidePackage, "1.17.0", repoSidePackageLocation, LocationType.NugetFeed)];
        List<AssetData> vmrSideAssets = [GetAssetDataWithLocations(vmrSidePackage, "2.17.0", vmrSidePackageLocation, LocationType.NugetFeed)];
        List<AssetData> source1Assets = [GetAssetDataWithLocations(buildPackage, "3.1.0", buildPackageLocation, LocationType.NugetFeed)];
        List<AssetData> pinnedAssets = GetAssetData(pinnedArcade, "1.1.0", pinnedPackage, "2.1.0");
        List<AssetData> source1AssetsUpdated = [GetAssetDataWithLocations(buildPackage, "3.17.0", buildPackageLocation, LocationType.NugetFeed)];
        List<AssetData> updatedPinnedAssets = GetAssetData(pinnedArcade, "1.17.0", pinnedPackage, "2.17.0");

        TemporaryDirectory testRepoFolder = await CloneRepositoryAsync(TestRepository.TestRepo2Name);
        string sourceRepoUri = GetGitHubRepoUrl(TestRepository.VmrTestRepoName);
        TemporaryDirectory vmrFolder = await CloneRepositoryAsync(TestRepository.VmrTestRepoName);
        var newFilePath = Path.Combine(vmrFolder.Directory, "src", TestRepository.TestRepo2Name, TestFile1Name);

        await CreateBuildAsync(sourceRepoUri, branchName, RepoSideDependencyCommit, "repo-side-location", repoSideAssets);
        await CreateBuildAsync(sourceRepoUri, branchName, VmrSideDependencyCommit, "vmr-side-location", vmrSideAssets);

        await CreateTargetBranchAndExecuteTest(targetBranchName, testRepoFolder.Directory, async () =>
        {
            TestContext.WriteLine("Adding dependencies to target repo");
            await AddDependenciesToLocalRepo(testRepoFolder.Directory, repoSideAssets, sourceRepoUri, commit: RepoSideDependencyCommit);
            await AddDependenciesToLocalRepo(testRepoFolder.Directory, source1Assets, sourceRepoUri, commit: BuildDependencyInitialCommit);
            await AddDependenciesToLocalRepo(testRepoFolder.Directory, pinnedAssets, sourceRepoUri, pinned: true);

            TestContext.WriteLine("Pushing branch to remote");
            await GitCommitAsync("Add dependencies");

            await using (await PushGitBranchAsync("origin", targetBranchName))
            {
                using (ChangeDirectory(vmrFolder.Directory))
                {
                    await using (await CheckoutBranchAsync(branchName))
                    {
                        // Make a change in the VMR
                        TestContext.WriteLine("Making code changes in the VMR");
                        await AddDependenciesToLocalRepo(
                            vmrFolder.Directory,
                            vmrSideAssets,
                            sourceRepoUri,
                            commit: VmrSideDependencyCommit,
                            relativeBasePath: $"src/{TestRepository.TestRepo2Name}");
                        File.WriteAllText(newFilePath, TestFilesContent[TestFile1Name]);

                        await GitAddAllAsync();
                        await GitCommitAsync($"Change that would have been made in a pr (#{includedPrNumber})");

                        // A change outside of src/<repo> in the VMR - must NOT be linked in the backflow PR comment
                        var outsideRepoFilePath = Path.Combine(vmrFolder.Directory, "outsideRepoFile.txt");
                        await File.WriteAllTextAsync(outsideRepoFilePath, "test");
                        await GitAddAllAsync();
                        await GitCommitAsync($"Change outside the repo folder (#{excludedPrNumber})");

                        // Push it to github
                        await using (await PushGitBranchAsync("origin", branchName))
                        {
                            var repoSha = (await GitGetCurrentSha()).TrimEnd();

                            // Create a new build from the commit and add it to a channel
                            Build build = await CreateBuildAsync(
                                GetGitHubRepoUrl(TestRepository.VmrTestRepoName),
                                branchName,
                                repoSha,
                                "1",
                                [ ..source1AssetsUpdated, ..updatedPinnedAssets ]);

                            TestContext.WriteLine("Adding build to channel");
                            await AddBuildToChannelAsync(build.Id, channelName);

                            TestContext.WriteLine("Triggering the subscription");
                            // Now trigger the subscription
                            await TriggerSubscriptionAsync(subscriptionId);

                            TestContext.WriteLine("Verifying subscription PR");
                            var assetsToVerify = pinnedAssets
                                .Concat(repoSideAssets)
                                .Concat(vmrSideAssets)
                                .Concat(source1AssetsUpdated)
                                .Select(a => new DependencyDetail() { Name = a.Name, Version = a.Version}).ToList();
                            var pr = await CheckBackwardFlowGitHubPullRequest(
                                TestRepository.VmrTestRepoName,
                                TestRepository.TestRepo2Name,
                                targetBranchName,
                                [TestFile1Name],
                                TestFilePatches,
                                assetsToVerify,
                                repoSha,
                                build.Id,
                                [repoSidePackageLocation, vmrSidePackageLocation, buildPackageLocation]);

                            var vmrRepoUrl = GetGitHubRepoUrl(TestRepository.VmrTestRepoName);
                            await CheckIfPullRequestCommentExists(
                                TestRepository.TestRepo2Name,
                                pr,
                                [$"{vmrRepoUrl}/pull/{includedPrNumber}"]);

                            await CheckThatPullRequestCommentDoesNotContain(
                                TestRepository.TestRepo2Name,
                                pr,
                                [$"{vmrRepoUrl}/pull/{excludedPrNumber}"]);
                        }
                    }
                }
            }
        });
    }


}
