stages:
- stage: ApproveDeploymentBi
  displayName: Approve BI
  dependsOn:
  - Build
  jobs:
  - deployment: approval
    displayName: Build Insights - deployment approval (conditional)
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/production') }}:
      environment: Production
    ${{ else }}:
      environment: Staging
    pool: server

- stage: MigrationsBi
  displayName: Migrate BI
  dependsOn:
  - Build
  - ApproveDeploymentBi
  jobs:
  - job: UpdateDatabase
    displayName: Update Build Insights database
    pool:
      name: NetCore1ESPool-Internal
      demands: ImageOverride -equals 1es-windows-2022
    variables:
    - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/production') }}:
      - name: buildInsightsSqlServerName
        value: build-insights-sql
      - name: buildInsightsDatabaseName
        value: BuildInsights
    - ${{ else }}:
      - name: buildInsightsSqlServerName
        value: build-insights-sql-int
      - name: buildInsightsDatabaseName
        value: BuildInsights
    steps:
    - download: current
      displayName: Download BuildInsightsCli
      artifact: BuildInsightsCli

    - powershell: |
        $az = Get-Command az.cmd
        Write-Host "##vso[task.setvariable variable=azCliPath]$($az.Source)"
      displayName: Locate Azure CLI

    - task: AzureCLI@2
      displayName: Entity Framework update
      inputs:
        azureSubscription: $(pcsDeploymentServiceConnection)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
            Write-Host "Running EF Core migrations for SQL Server: $(buildInsightsSqlServerName), Database: $(buildInsightsDatabaseName)"
            $connectionString = "Server=tcp:$(buildInsightsSqlServerName).database.windows.net,1433;Database=$(buildInsightsDatabaseName);Encrypt=True;TrustServerCertificate=False;Connection Timeout=30"
            $(Pipeline.Workspace)/BuildInsightsCli/BuildInsightsCli.exe migrate --connection-string $connectionString

- stage: DeployBi
  displayName: Deploy BI
  dependsOn:
  - Build
  - ApproveDeploymentBi
  - MigrationsBi

  variables:
  - name: currentDate
    value: $[format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime)]
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/production') }}:
    - name: biSubscriptionId
      value: e6b5f9f5-0ca4-4351-879b-014d78400ec2
    - name: biResourceGroupName
      value: build-insights-rg
    - name: biContainerAppName
      value: build-insights-int
    - name: biContainerJobNames
      value: build-insights-job-int
    - name: biContainerAppWorkspaceName
      value: build-insights-log-int
    - name: biRedisConnectionString
      value: "build-insights-redis-int.redis.cache.windows.net:6380,ssl=true"
  - ${{ else }}:
    - name: biSubscriptionId
      value: e6b5f9f5-0ca4-4351-879b-014d78400ec2
    - name: biResourceGroupName
      value: build-insights-rg
    - name: biContainerAppName
      value: build-insights-int
    - name: biContainerJobNames
      value: build-insights-job-int
    - name: biContainerAppWorkspaceName
      value: build-insights-log-int
    - name: biRedisConnectionString
      value: "build-insights-redis-int.redis.cache.windows.net:6380,ssl=true"

  jobs:
  - job: DeployBuildInsights
    displayName: Deploy Build Insights
    pool:
      name: NetCore1ESPool-Internal
      demands: ImageOverride -equals 1es-windows-2022
    variables:
      newDockerImageTag: $[stageDependencies.Build.BuildAndPublishDocker.outputs['DockerTag.newDockerImageTag']]

    steps:
    - download: current
      displayName: Download BuildInsightsCli
      artifact: BuildInsightsCli

    - task: UseDotNet@2
      displayName: Install .NET
      inputs:
        useGlobalJson: true

    - powershell: |
        $az = Get-Command az.cmd
        Write-Host "##vso[task.setvariable variable=azCliPath]$($az.Source)"
      displayName: Locate Azure CLI

    # We'll need to give this service connection permission to get an auth token for PCS
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(pcsDeploymentServiceConnection)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: >
          $(Pipeline.Workspace)/BuildInsightsCli/BuildInsightsCli.exe
          deploy
          --subscriptionId $(biSubscriptionId)
          --resourceGroupName $(biResourceGroupName)
          --containerRegistryName $(buildInsightsContainerRegistryName)
          --containerAppName $(biContainerAppName)
          --containerJobNames $(biContainerJobNames)
          --workspaceName $(biContainerAppWorkspaceName)
          --newImageTag $(newDockerImageTag)
          --imageName dummy-app
          --attempt $(System.JobAttempt)
          --azCliPath "$(azCliPath)"
          --redisConnectionString $(biRedisConnectionString)
      displayName: Deploy container app

